#pragma once

#include <unordered_map>


static const std::string FileTypeStr[]
{
	"Unknown",
	"Arena",
	"LvlMaze",
	"LvlWarp",
	"Properties",
	"AutoMagic",
	"UniqueItems",
	"SetItems",
	"Runes",
	"PetTypes",
	"Inventory",
	"Belts",
	"Automap",
	"States",
	"Objects",
	"Levels",
	"ItemStatCost",
	"Missiles",
	"DifficultyLevels",
	"CubeMain",
	"CharStats",
	"MonStats",
	"Skills",
	"SkillDesc",
	"Items",
};
enum class FileType
{
	Unknown,
	Arena,
	BodyLocs,
	LvlMaze,
	LvlWarp,
	Properties,
	AutoMagic,
	UniqueItems,
	SetItems,
	Runes,
	PetTypes,
	Inventory,
	Belts,
	AutoMap,
	States,
	Objects,
	Levels,
	ItemStatCost,
	Missiles,
	DifficultyLevels,
	CubeMain,
	CharStats,
	MonStats,
	Skills,
	SkillDesc,
	Items,
};

const std::unordered_map<std::string, FileType> matchingFiles = {
	{"arena.bin", FileType::Arena},
	{"armor.bin", FileType::Items},
	{"armtype.bin", FileType::Unknown},
	{"automagic.bin", FileType::AutoMagic},
	{"automap.bin", FileType::AutoMap},
	{"belts.bin", FileType::Belts},
	{"bodylocs.bin", FileType::BodyLocs},
	{"books.bin", FileType::Unknown},
	{"charstats.bin", FileType::CharStats},
	{"chartemplate.bin", FileType::Unknown},
	{"colors.bin", FileType::Unknown},
	{"compcode.bin", FileType::Unknown},
	{"composit.bin", FileType::Unknown},
	{"cubemain.bin", FileType::CubeMain},
	{"difficultylevels.bin", FileType::DifficultyLevels},
	{"elemtypes.bin", FileType::Unknown},
	{"events.bin", FileType::Unknown},
	{"experience.bin", FileType::Unknown},
	{"gamble.bin", FileType::Unknown},
	{"gems.bin", FileType::Unknown},
	{"hiredesc.bin", FileType::Unknown},
	{"hireling.bin", FileType::Unknown},
	{"hitclass.bin", FileType::Unknown},
	{"inventory.bin", FileType::Inventory},
	{"itemratio.bin", FileType::Unknown},
	{"itemscode.bin", FileType::Unknown},
	{"itemstatcost.bin", FileType::ItemStatCost},
	{"itemtypes.bin", FileType::Unknown},
	{"leveldefs.bin", FileType::Unknown},
	{"levels.bin", FileType::Levels},
	{"lowqualityitems.bin", FileType::Unknown},
	{"lvlmaze.bin", FileType::Unknown},
	{"lvlprest.bin", FileType::Unknown},
	{"lvlsub.bin", FileType::Unknown},
	{"lvltypes.bin", FileType::Unknown},
	{"lvlwarp.bin", FileType::Unknown},
	{"magicprefix.bin", FileType::AutoMagic},
	{"magicsuffix.bin", FileType::AutoMagic},
	{"misc.bin", FileType::Items},
	{"misscalc.bin", FileType::Unknown},
	{"misscode.bin", FileType::Unknown},
	{"missiles.bin", FileType::Missiles},
	{"monai.bin", FileType::Unknown},
	{"monequip.bin", FileType::Unknown},
	{"monitempercent.bin", FileType::Unknown},
	{"monlvl.bin", FileType::Unknown},
	{"monmode.bin", FileType::Unknown},
	{"monplace.bin", FileType::Unknown},
	{"monpreset.bin", FileType::Unknown},
	{"monprop.bin", FileType::Unknown},
	{"monseq.bin", FileType::Unknown},
	{"monsounds.bin", FileType::Unknown},
	{"monstats.bin", FileType::MonStats},
	{"monstats2.bin", FileType::MonStats},
	{"montype.bin", FileType::Unknown},
	{"monumod.bin", FileType::Unknown},
	{"npc.bin", FileType::Unknown},
	{"objects.bin", FileType::Objects},
	{"objgroup.bin", FileType::Unknown},
	{"objmode.bin", FileType::Unknown},
	{"objtype.bin", FileType::Unknown},
	{"overlay.bin", FileType::Unknown},
	{"pettype.bin", FileType::PetTypes},
	{"playerclass.bin", FileType::Unknown},
	{"plrmode.bin", FileType::Unknown},
	{"plrtype.bin", FileType::Unknown},
	{"properties.bin", FileType::Unknown},
	{"qualityitems.bin", FileType::Unknown},
	{"rareprefix.bin", FileType::Unknown},
	{"raresuffix.bin", FileType::Unknown},
	{"runes.bin", FileType::Runes},
	{"setitems.bin", FileType::SetItems},
	{"sets.bin", FileType::Unknown},
	{"shrines.bin", FileType::Unknown},
	{"skillcalc.bin", FileType::Unknown},
	{"skilldesc.bin", FileType::SkillDesc},
	{"skilldesccode.bin", FileType::Unknown},
	{"skills.bin", FileType::Skills},
	{"skillscode.bin", FileType::Unknown},
	{"sounds.bin", FileType::Unknown},
	{"states.bin", FileType::States},
	{"storepage.bin", FileType::Unknown},
	{"superuniques.bin", FileType::Unknown},
	{"treasureclassex.bin", FileType::Unknown},
	{"uniqueappellation.bin", FileType::Unknown},
	{"uniqueitems.bin", FileType::UniqueItems},
	{"uniqueprefix.bin", FileType::Unknown},
	{"uniquesuffix.bin", FileType::Unknown},
	{"uniquetitle.bin", FileType::Unknown},
	{"weapons.bin", FileType::Items},
};